name: Update S3 Counts

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-counts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install boto3

      - name: Run update script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          REGION_NAME: ${{ secrets.AWS_REGION }}
          MACHINE_IDS: ${{ secrets.MACHINE_IDS }}
        run: python update_s3_counts.py

      - name: Commit & Push Changes
        env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
           git config user.name "GitHub Actions"
           git config user.email "actions@github.com"
           git add data_counts.json last_processed.json
           git commit -m "Update data counts" || echo "No changes"
           git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
           # 변경사항 가져오기 + 커밋 합병 + 강제 푸시
           git pull --rebase origin ${{ github.ref_name }}
           git push origin HEAD:${{ github.ref_name }}
